### ISSUE TITLE
[BUG] Error handling of JSON.parse in nostr-fetch 

### ISSUE THREAD

**Issue by atrifat** [jiftechnify/nostr-fetch#128]
Hello jiftechnify-san. I'm not sure how to reproduce this error, but this is the last error that i got when i'm using nosdump. As far as i know, nosdump actually uses nostr-fetch right? 

This is error log that i can get:
```
[ws://127.0.0.1:7778/] FetchTillEoseFailedSignal: WebSocket error
failed to parse R2C message as JSON: SyntaxError: Unterminated string in JSON at position 514
    at JSON.parse (<anonymous>)
    at En (file:///tmp/deno-compile-nosdump/node_modules/localhost/nostr-fetch/0.13.0/dist/index.mjs:1:34827)
    at Bt.handleMsgs (file:///tmp/deno-compile-nosdump/node_modules/localhost/nostr-fetch/0.13.0/dist/index.mjs:1:37685)
    at Timeout._onTimeout (file:///tmp/deno-compile-nosdump/node_modules/localhost/nostr-fetch/0.13.0/dist/index.mjs:1:38504)
    at cb (ext:deno_node/internal/timers.mjs:63:31)
    at Object.action (ext:deno_web/02_timers.js:153:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:67:10)
    at eventLoopTick (ext:core/01_core.js:189:21)
```

I'm using strfry 0.9.6 as my local relay and nosdump 0.4.2.

Thank you.

**Comment by jiftechnify** [comment]
Thank you for reporting the issue, atrifat-san!  And I'm sorry for late response🙇

You are right, nosdump uses nostr-fetch under the hood.

I'm not certain but it seems that the WebSocket connection is disconnected abruptly due to error in the remote side (strfry). Does it happen every time you use nosdump with your local relay?

**Comment by atrifat** [comment]
It is ok Takumi-san, thank you that you've finally notice this issue. I'm sure that you were busy working on something else.

It is not happen every time. As you have suspected, i agree that it is due to error remote side and it is not happen only on my relay. I have similar issue with other public relays.

I will provide more detail explanation, full bash script and try to reproduce the issue later to help cover this issue.

**Comment by atrifat** [comment]
The following bash script (sync.sh) can reproduce the issue, but it still depends on whether relays reject request and close connection immediately.
```bash
#!/usr/bin/env bash
sync(){
nosdump --skip-verification --kinds 1 --since $(( $(date +%s) - 86400 * 31)) --until $(( $(date +%s) - 60 * 1)) \
  wss://relay.nostr.wirednet.jp wss://njump.me wss://relayable.org wss://nos.lol wss://relay.damus.io wss://relay.mostr.pub wss://relay.shitforce.one wss://yabu.me wss://nostr.fmt.wiz.biz wss://relay.nostr.bg wss://purplerelay.com
}

sync & true
```

We can execute it with `bash sync.sh` and will get the following errors. Although, the relays which gives errors are not always the same.

```bash
[wss://relay.nostr.wirednet.jp/] FetchTillEoseFailedSignal: WebSocket error                                                         
failed to parse R2C message as JSON: SyntaxError: Unterminated string in JSON at position 384 (line 1 column 385)
    at JSON.parse (<anonymous>)                                       at En (file:///home/admin/.cache/deno/npm/registry.npmjs.org/nostr-fetch/0.13.0/dist/index.mjs:1:34827)
    at Bt.handleMsgs (file:///home/admin/.cache/deno/npm/registry.npmjs.org/nostr-fetch/0.13.0/dist/index.mjs:1:37685)
    at Timeout._onTimeout (file:///home/admin/.cache/deno/npm/registry.npmjs.org/nostr-fetch/0.13.0/dist/index.mjs:1:38504)             at cb (ext:deno_node/internal/timers.mjs:63:31)                   at Object.action (ext:deno_web/02_timers.js:150:11)               at handleTimerMacrotask (ext:deno_web/02_timers.js:64:10)         at eventLoopTick (ext:core/01_core.js:184:21)
    
[wss://relay.shitforce.one/] FetchTillEoseFailedSignal: WebSocket error                                                             
failed to parse R2C message as JSON: SyntaxError: Unterminated string in JSON at position 615 (line 1 column 616)                       at JSON.parse (<anonymous>)                                       at En (file:///home/admin/.cache/deno/npm/registry.npmjs.org/nostr-fetch/0.13.0/dist/index.mjs:1:34827)                             at Bt.handleMsgs (file:///home/admin/.cache/deno/npm/registry.npmjs.org/nostr-fetch/0.13.0/dist/index.mjs:1:37685)                  at Timeout._onTimeout (file:///home/admin/.cache/deno/npm/registry.npmjs.org/nostr-fetch/0.13.0/dist/index.mjs:1:38504)             at cb (ext:deno_node/internal/timers.mjs:63:31)
    at Object.action (ext:deno_web/02_timers.js:150:11)               at handleTimerMacrotask (ext:deno_web/02_timers.js:64:10)
    at eventLoopTick (ext:core/01_core.js:184:21)

```

After looking at implementation in nostr-fetch [ (Kernel package, nostr.ts, line 122)](https://github.com/jiftechnify/nostr-fetch/blob/a56a898d93b26b723d837669d6694cb2b40bd036/packages/kernel/src/nostr.ts#L122C1-L122C5), i think this is not really problem, since you have already capture it in catch block, right? I thought it was uncaught error at first.

What do you think, Takumi-san?

**Comment by jiftechnify** [comment]
Yeah, nostr-fetch ignores (just logs to stderr) problems while parsing Nostr messages by design.  I think it works as expected.
